rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    # Show category by slug
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    # Add category
    path('add_category/', views.add_category, name='add_category'),
    # Add page
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('restricted/', views.restricted, name='restricted'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rango import views 

urlpatterns = [
    path('', views.index, name='index'), 
    path('admin/', admin.site.urls),
    path('rango/', include('rango.urls')),
    path('about/', views.about, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    NAME_MAX_LENGTH = 128  # Avoid repeating magic numbers
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, default='')

    def save(self, *args, **kwargs):
        # Automatically generate a slug if the name changes
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField(max_length=URL_MAX_LENGTH)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    # We can reuse the model's NAME_MAX_LENGTH constant
    name = forms.CharField(
        max_length=Category.NAME_MAX_LENGTH,
        help_text="Please enter the category name."
    )
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        # Only want to show the name field to the user
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(
        max_length=Page.TITLE_MAX_LENGTH,
        help_text="Please enter the title of the page."
    )
    url = forms.URLField(
        max_length=Page.URL_MAX_LENGTH,
        help_text="Please enter the URL of the page."
    )
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        # Exclude the category field since we'll set it in the view
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is provided and doesn't start with "http://"
        # or "https://", prepend "http://"
        if url:
            if not (url.startswith('http://') or url.startswith('https://')):
                url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
 class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import render
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

def get_server_side_cookie(request, cookie, default_val=None):

    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):

    # 1. 获取访问次数，默认为 '1'
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    # 2. 获取上次访问时间，若不存在则设为当前时间
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    # 3. 如果距离上次访问超过一天，则增加访问次数
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        # 否则只更新 last_visit
        request.session['last_visit'] = last_visit_cookie

    # 4. 写回访问次数
    request.session['visits'] = visits

def index(request):
    # 获取最受欢迎的 5 个分类
    category_list = Category.objects.order_by('-likes')[:5]
    # 获取浏览量最高的 5 个页面
    page_list = Page.objects.order_by('-views')[:5]

    # 构建上下文字典
    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!',
        'categories': category_list,
        'pages': page_list,
    }

    # 1. 提前获得 response 对象，以便在其中设置 Cookie
    response = render(request, 'rango/index.html', context=context_dict)

    # 2. 调用辅助函数，处理客户端 Cookie（增加/更新）
    visitor_cookie_handler(request, response)

    # 3. 返回 response，完成 Cookie 的写入或更新
    return response

def about(request):
    return render(request, 'rango/about.html')

def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['category'] = category
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=True)
            # 保存后可重定向到首页或其它页面
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    # 若分类不存在，则跳回首页
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0  # 或者任意默认值
            page.save()
            # 保存成功后跳回该分类详情页
            return redirect(reverse('rango:show_category',
                                    kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # 使用 set_password() 将明文密码转换为哈希值
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # 如果用户上传了头像文件
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
        else:
            # 输出错误信息以便调试
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account has been disabled.")
        else:
            print(f"Login failed: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")

rango/templates/rango/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>About Rango</title>
</head>
<body>
    <h1>Rango says...</h1>
    <p>here is the about page.</p>

    <div>
        <a href="{% url 'rango:about' %}">About</a>
    </div>

    <div>
        <!-- 显示静态文件中的 Rango 图片 -->
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>

    <div>
        <!-- 显示媒体文件中的 cat.jpg 图片 (用户上传) -->
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>

    <div>
        <!-- 显示你的名字或其他信息 -->
        <p>{{ boldmessage }}</p>
    </div>
</body>
</html>

rango/templates/rango/add_category.html
{% extends "rango/base.html" %}
{% load static %}

{% block title_block %}
  Rango - Add Category
{% endblock %}

{% block body_block %}
  <h1>Add a Category</h1>
  <div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
      {% csrf_token %}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br />
        {{ field }}<br /><br />
      {% endfor %}

      <input type="submit" name="submit" value="Create Category" />
    </form>
  </div>
{% endblock %}

rango/templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load static %}

{% block title_block %}
  Rango - Add Page
{% endblock %}

{% block body_block %}
  {% if category %}
    <h1>Add a Page to {{ category.name }}</h1>
    <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
      {% csrf_token %}

      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}

      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br />
        {{ field }}<br /><br />
      {% endfor %}

      <input type="submit" name="submit" value="Create Page" />
    </form>
  {% else %}
    <p>The specified category does not exist.</p>
  {% endif %}
{% endblock %}

rango/templates/rango/base.html
{% load staticfiles %}
{% load rango_template_tags %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>
      Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
</head>
<body>
    <div>
      {% block body_block %}{% endblock %}
    </div>

    <!-- Sidebar with categories -->
    <div>
      {% block sidebar_block %}
        {% get_category_list category %}
      {% endblock %}
    </div>

    <hr />
    <div>
      <ul>
        {% if user.is_authenticated %}
        <!-- Show these links when the user is logged in-->
        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
        <li><a href="{% url 'rango:logout' %}">Logout</a></li>
        {% else %}
        <!-- Show these links when the user is NOT logged in-->
        <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
        <li><a href="{% url 'rango:login' %}">Login</a></li>
        {% endif %}
        <!-- Outside the conditional statements, ALWAYS show-->
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>
</html>

rango/templates/rango/categories.html
<ul>
    {% if categories %}
      {% for c in categories %}
        {% if c == current_category %}
          <li>
            <strong>
              <a href="{% url 'rango:show_category' c.slug %}">
                {{ c.name }}
              </a>
            </strong>
          </li>
        {% else %}
          <li>
            <a href="{% url 'rango:show_category' c.slug %}">
              {{ c.name }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    {% else %}
      <li><strong>There are no categories present.</strong></li>
    {% endif %}
  </ul>
  

rango/templates/rango/category.html
{% extends "rango/base.html" %}
{% load static %}

{% block title_block %}
  Category Details{% if category %} - {{ category.name }}{% endif %}
{% endblock %}

{% block body_block %}
  <div>
    {% if category %}
      <h1>{{ category.name }}</h1>
      <!-- 返回首页的链接 -->
      <p><a href="{% url 'rango:index' %}">Back to Home</a></p>
      <!-- 添加页面的链接，传入 category.slug 作为参数 -->
      <p><a href="{% url 'rango:add_page' category.slug %}">Add a Page</a></p>

      {% if pages %}
        <ul>
          {% for page in pages %}
            <li>
              <a href="{{ page.url }}">{{ page.title }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <strong>No pages currently in category.</strong>
      {% endif %}
    {% else %}
      <p>The specified category does not exist.</p>
    {% endif %}
  </div>
{% endblock %}

rango/templates/rango/index.html
{% extends "rango/base.html" %}
{% load static %}

{% block title_block %}
  Rango
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1>
  <div>
    {% if user.is_authenticated %}
      howdy {{ user.username }}!<br/>
    {% else %}
      hey there partner!<br/>
    {% endif %}
    <strong>{{ boldmessage }}</strong>
  </div>
  
  <div>
    <h2>Most Liked Categories</h2>
    {% if categories %}
      <ul>
        {% for category in categories %}
          <li>
            <!-- 使用 category.slug 动态生成链接 -->
            <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>There are no categories present.</strong>
    {% endif %}
  </div>
  
  <div>
    <h2>Most Viewed Pages</h2>
    {% if pages %}
      <ul>
        {% for page in pages %}
          <li>
            <!-- 如果 page.url 已经正确生成相对 URL，可以保持不变 -->
            <a href="{{ page.url }}">{{ page.title }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>There are no pages present.</strong>
    {% endif %}
  </div>
  
  <div>
    <a href="{% url 'rango:about' %}">About Rango</a><br />
    <a href="{% url 'rango:add_category' %}">Add a New Category</a><br />
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
  </div>
{% endblock %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
  Log in 
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        <p>
            username: <input type="text" name="username" size="50">
        </p>
        <p>
            password: <input type="password" name="password" size="50">
        </p>
        <input type="submit" value="Log in">
    </form>
{% endblock %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
  Rango says: <strong>thank you for registering!</strong>
  <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
  Rango says: <strong>register here!</strong><br/>
  <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Display each form -->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
  </form>
{% endif %}
{% endblock %}